[BB] column 타이틀 옆 +, x 버튼 이벤트
healtheloper/todo-list pull request #58
Opened 2022-04-13 14:06 UTC by BB-choi

issue #11

+ 버튼, x버튼 마우스오버시 색상변경
+ 버튼 클릭시 `새로운 카드를 등록할 수 있는 박스`가 나오고, 다시 클릭시 사라짐
x 버튼 클릭시 아무 일도 일어나지 않음
`새로운 카드를 등록할 수 있는 박스`에서 취소버튼 클릭시 사라짐

마구마구 리뷰 부탁드려요오오요옹 🙌

2022-04-13 14:30 UTC, healtheloper requested changes
고생하셨습니다 비비~~
리뷰 마구마구 드립니다~~ ㅋㅋ

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/CardWritable/CardWritable.js
> +    child: [],
지금 저희 createElement 로직이 child 안넣어주면 오류나나요??

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/CardWritable/CardWritable.js
> +  });
저희 tagComponents 에서 만든 Button 쓰셔도 될듯?!

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/ColumnHeader/ColumnHeader.js
> +      </svg>`,
태그가 긴 것은 따로 변수명으로 작성해서 넣는게 좋아보일 것 같아요!

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/ColumnHeader/ColumnHeader.js
> +    ],
display block, none 으로 CardWritable 이 맨 위에서 사용되는 로직이 매우 흥미로웠는네요 ㅎㅎ 그런데 이 위치에서 적용이 된다면 혹시 Card 를 수정해야 하는 상황이라면 CardWritable 을 활용할 수 있을까? CSS 가 제대로 적용이될까? 라는 생각이 들었어요

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/ColumnHeader/ColumnHeader.js
> +
1. 클래스 이름을 postcss 가 빌드되면서 난독화가 되고있는데, 임의로 이렇게 써도 될까?
2.  querySelector 로 찾아오는게 최선일까?! 핸들러를 만들어서 핸들러를 넘겨줘서 관리할 수는 없을까? 라는 고민이 드는데, CardWritable 의 위치를 이야기해보고 고민해봐야 할 것같아요

2022-04-13 14:30 UTC, healtheloper commented on front/src/components/Content/CardWritable/CardWritable.js
> +  });
핸들러를 넘겨줘서 관리한다고 쳤을 때, 해당 태그를 바로 return 하지 않고 $cardWritable 과 같이 선언한 이후, $cardWritable 의 클래스를 toggle 하는 방법이 떠오르는데, 이 부분도 같이 얘기해보면 좋을 것 같네요~!

2022-04-13 14:32 UTC, BB-choi commented on front/src/components/Content/ColumnHeader/ColumnHeader.js
> +      </svg>`,
createElement로 바꾸다가 나중에 빼야지 하다가 까먹은 부분이네요!! 수정하겠습니다

2022-04-13 14:32 UTC, BB-choi commented on front/src/components/Content/CardWritable/CardWritable.js
> +    child: [],
네~! 없으니까 오류가 나는 걸로 보고 추가 해봤었는데 다시 한 번 확인해보겠습니다!!!

2022-04-13 14:33 UTC, BB-choi commented on front/src/components/Content/CardWritable/CardWritable.js
> +  });
👍👍👍

2022-04-13 14:34 UTC, healtheloper commented on front/src/components/Content/CardWritable/CardWritable.js
> +    child: [],
그렇군요,, core 로직을 수정하는게 맞아보이네요 ㅎㅎ

2022-04-13 14:40 UTC, BB-choi commented on front/src/components/Content/ColumnHeader/ColumnHeader.js
> +
1. 이 부분은 어떻게 해야할까 고민을 하다가
```js
return peact.createElement({
    tag: "div",
    className: [styles.cardWritable, "cardWritable", styles.hidden],
    child: [$cardWritableHeader, $inputDesc, $buttonArea],
  });
```
와 같이 ` "cardWritable"`문자열로 만들었습니다...ㅎㅠ

2. 넵 맞아요 같이 얘기 나눠보면 좋을 것 같습니다!!

2022-04-13 14:41 UTC, BB-choi commented on front/src/components/Content/CardWritable/CardWritable.js
> +  });
🙌네 같이 얘기 나누어보면 좋겠습니답

2022-04-14 05:51 UTC, healtheloper approved these changes

2022-04-14 06:11 UTC, merged